<h2><img src="<?php echo $this->baseUrl('/ui/images/icons/user_32.png')?>" alt="Login" />Giriş</h2>

        <div class="content-box">
                <div class="content-box-header">
                        <h3>Giriş</h3>
                </div>
            
                <div class="content-box-content">
                    <?php if (isset($this->auth) && $this->auth == false){ ?>
                    <div class="notification information">Kullanıcı adınız veya Parolanız hatalı.</div>
                    <?php } 
                    echo $this->form;
                    ?>
                </div>
        </div>

