<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Travel - About</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/ui/default/css/style.css')?>" />
</head>

<body>
	<div id="header">
		<a href="index.html" class="logo"><img src="<?php echo $this->baseUrl('/ui/default/images/logo.png')?>" alt="" width="274" height="90" /></a>																																								<div class="inner_copy"><a href="http://www.greatdirectories.org/categories/travel-directories/">free travel directories</a><a href="http://www.bestfreetemplates.org/categories/travel/">free travel templates</a></div>
	    <div>
			<span>Currency: </span>
			<select id="select">
				<option>US Dollar</option>
				<option>Euro</option>
			</select>
		  <span>Languages: </span>
		  <a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/l1.gif')?>" alt="" width="19" height="11" /></a>
		  <a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/l2.gif')?>" alt="" width="19" height="11" /></a>
		  <a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/l3.gif')?>" alt="" width="19" height="11" class="active" /></a>
		  <a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/l4.gif')?>" alt="" width="19" height="11" /></a>
		  <a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/l5.gif')?>" alt="" width="19" height="11" /></a>
		  <span id="account"><a href="#">My Account</a> | <a href="#">Shopping cart</a></span>																																																																		<div class="inner_copy"><a href="http://www.bestfreetemplates.info/">free website templates</a><a href="http://www.beautifullife.info/">luxury lifestyle</a></div>
		</div>
		<ul id="menu">
			<li><a href="#">Home Page</a></li>
			<li><a href="#">About Company</a></li>
			<li><a href="#">Hot Tours</a></li>
			<li><a href="#">Hotels</a></li>
			<li><a href="#">Services</a></li>
			<li><a href="#">Reviews</a></li>
			<li><a href="#">Partners</a></li>
			<li><a href="#">Contact us</a></li>																																																																							<div class="inner_copy"><a href="http://www.bestfreetemplates.org/">free templates</a><a href="http://www.bannermoz.com/">banner templates</a></div>
		</ul>
	</div>
	<div id="content">
            <?php echo $this->layout()->content; ?>
	</div>
	<div id="footer">
		<ul>
			<li><a href="#">Home Page</a> |</li>
			<li><a href="#">About Company</a> |</li>
			<li><a href="#">Hot Tours</a> |</li>
			<li><a href="#">Hotels</a> |</li>
			<li><a href="#">Services</a> |</li>
			<li><a href="#">Reviews</a> |</li>
			<li><a href="#">Partners</a> |</li>
			<li><a href="#">Contact us</a></li>
		</ul>
		<p>Copyright &copy;</p>																																																			<div class="inner_copy"><a href="http://www.greatdirectories.org/offer.html">buy links with high pr</a><a href="http://www.bestfreetemplates.org/">free website templates</a></div>
	</div>
</body>
</html>