  	  <div id="main">
	  		<p><a href="#" class="style4">Tours</a>  &raquo; Maldives</p>
  	  	  <img src="<?php echo $this->baseUrl('/ui/default/images/title8.gif')?>" alt="" width="134" height="37" />
		 	 <div id="gallery">
				  <img src="<?php echo $this->baseUrl('/ui/default/images/big.jpg')?>" alt="" width="476" height="355" />
				  <div>
				  	<a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/p1.jpg')?>" alt="" /></a>
				  	<a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/p2.jpg')?>" alt="" /></a>
				  	<a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/p3.jpg')?>" alt="" /></a>
				  	<a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/p4.jpg')?>" alt="" /></a>
				  	<a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/p5.jpg')?>" alt="" /></a>
				  	<a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/p6.jpg')?>" alt="" /></a>
				  	<a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/p7.jpg')?>" alt="" /></a>
				  	<a href="#"><img src="<?php echo $this->baseUrl('/ui/default/images/p8.jpg')?>" alt="" /></a>
					<a href="#" class="view">View Gallery</a>
				  </div>
		 	 </div>
			 <div class="about">
			   <a href="#" id="banner"><img src="<?php echo $this->baseUrl('/ui/default/images/banner.jpg')?>" alt="" width="187" height="301" /></a>
			   <img src="<?php echo $this->baseUrl('/ui/default/images/title9.gif')?>" alt="" width="235" height="41" />
			   <p>Lorem ipsum dolor sit amet, sectetu adip scing varius interdum incid unt quis, libero. Aenean mturpis. Maecenas hendrerit masa laoreet iaculipede mnisl ulamcorper. Tellus er sodales enim, in tincidunt mauris in odio. Massa ac <a href="#">laoreet iaculipede</a> nisl ullam <a href="#">corpermassa</a>, ac consectetuer feipsum eget pede.  Proin nunc. Donec massa. Nulla pulvinar, nisl ac convallis nonummy, tellus eros sodales enim, in tincidunt mauris in odio.  massa ac laoreet iaculipede nisl ullamcorpermassa,consectetuer feipsum eget pede. Proin nunc. Donec massa. Nulla pulvinar, nisl ac convallis nonummy, tellus eros sodales enim, in tincidunt mauris in odi.Lorem ipsum dolor sit amet, consectetuer adipi scing elit.Mauris u tincidunt quis, libero. </p>
			   <p>Maecenas hendrerit, massa ac laoreet iaculipedenisl ullamcorpermassa, ac consectetuer feipsum eget pede. Proin nunc. <a href="#">Donec massa</a>. Nulla pulvinar, nisl ac convallis nonummy, tellus eros sodales enim, in tincidunt mauris in odio.  massa ac laoreet iaculipede nisl ullamcorpermassa, ac consectetuer feipsum eget pede. Proin nunc. Donec massa. Nulla pulvinar, nisl ac convallis nonummy, tellus eros sodales enim, in tincidunt mauris in odio.  massa ac laoreet iaculipede nisl ullamcorpermassa,consectetuer feipsum eget pede. Proin nunc. Donec massa. Nulla pulvinar, nisl ac convallis nonummy, tellus eros sodales enim, in tincidunt mauris in odio. </p>
			 </div>
	  </div>
        <div id="sidebar">
                <div class="news">
                        <img src="<?php echo $this->baseUrl('/ui/default/images/title10.gif')?>" alt="" width="98" height="18" /><br />
                        <div>
                                <span>25 march</span>
                                <p>Lorem ipsum dolor sit amet, sectetu adip scing varius interdum incid unt quis, libero. Aenean mturpis. Maecenas hendrerit masa laoreet iaculipede mnisl ulamcorper. Tellus er sodales enim, in tincidunt mauris.</p>
                                <a href="#" class="more2">more info</a>
                        </div>
                        <div>
                                <span>12 march</span>
                                <p>Lorem ipsum dolor sit amet, sectetu adip scing varius interdum incid unt quis, libero. Aenean mturpis. Maecenas hendrerit masa laoreet iaculipede mnisl ulamcorper. Tellus er sodales enim, in tincidunt mauris.</p>
                                <a href="#" class="more2">more info</a>
                        </div>
                        <a href="#" id="all">all news</a>
                </div>
                <div>
                        <img src="<?php echo $this->baseUrl('/ui/default/images/title11.gif')?>" alt="" width="198" height="41" />
                        <p>Lorem ipsum dolor sit amet, sectetu adip scing varius interdum incid unt quis, libero. Aenean mturpis. Maecenas hendrerit masa laoreet iaculipede mnisl ulamcorper. Tellus er sodales enim, in tincidunt mauris in odio. Massa ac laoreet iaculipede nisl ullamcorpermassa, ac consectetuer feipsum eget pede.  Proin nunc. Donec massa. Nulla pulvinar, nisl ac convallis nonummy, tellus eros sodales enim, in tincidunt mauris in odio.  massa ac laoreet iaculipede nisl ullamcorpermassa,consectetuer feipsum eget pede. Proin nunc. Donec massa. Nulla pulvinar, nisl ac convallis nonummy, tellus eros sodales enim, in tincidunt.</p>
                </div>
        </div>
